"""Utilities module."""

from .visualization import (
    plot_fc_comparison,
    plot_training_curves,
    plot_model_comparison,
    plot_timeseries,
    plot_realizations,
    plot_power_spectrum,
    plot_simulation_multigrid,
    create_comparison_report,
    FIGURES_DIR,
    _get_save_path
)
from .signal_pipeline import (
    SignalPipelineResult,
    prepare_signal_pipeline,
    plot_signal_pipeline,
)
from .runtime import (
    ensure_proxy_env,
    resolve_device,
    seed_all,
    print_section,
    wandb_active,
    init_wandb_run,
    wandb_log,
    wandb_summary_update,
    wandb_log_figure,
    wandb_log_artifact,
    finish_wandb_run,
    managed_wandb_run,
)
from .evaluation import (
    to_float_metric,
    prefixed_metrics,
    EVAL_METRIC_KEYS,
    generate_fc_figure,
    generate_multigrid_figure,
    save_checkpoint,
    log_hopf_best_params,
    extract_val_data,
    split_subject_indices,
    evaluate_hopf_model,
    evaluate_model_loader_metrics,
    evaluate_hopf_loader_metrics,
)
from .paper_pipeline import (
    run_paper_pipeline,
    run_update_tables,
    run_compare_models,
    run_compare_conditions,
)

__all__ = [
    "plot_fc_comparison",
    "plot_training_curves",
    "plot_model_comparison",
    "plot_timeseries",
    "plot_realizations",
    "plot_power_spectrum",
    "plot_simulation_multigrid",
    "SignalPipelineResult",
    "prepare_signal_pipeline",
    "plot_signal_pipeline",
    "create_comparison_report",
    "FIGURES_DIR",
    "_get_save_path",
    "ensure_proxy_env",
    "resolve_device",
    "seed_all",
    "print_section",
    "wandb_active",
    "init_wandb_run",
    "wandb_log",
    "wandb_summary_update",
    "wandb_log_figure",
    "wandb_log_artifact",
    "finish_wandb_run",
    "managed_wandb_run",
    "to_float_metric",
    "prefixed_metrics",
    "EVAL_METRIC_KEYS",
    "generate_fc_figure",
    "generate_multigrid_figure",
    "save_checkpoint",
    "log_hopf_best_params",
    "extract_val_data",
    "split_subject_indices",
    "evaluate_hopf_model",
    "evaluate_model_loader_metrics",
    "evaluate_hopf_loader_metrics",
    "run_paper_pipeline",
    "run_update_tables",
    "run_compare_models",
    "run_compare_conditions",
]
